language: python
matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
install:
    - pip install tox==3.0.0
    - pip install coveralls==1.3.0
    - pip install coverage==4.5.1
before_script:
    - coverage erase
script:
    - coverage run --source=delegator -m pytest tests.py; tox
after_success:
    - COVERALLS_REPO_TOKEN=pwBWtyxjIuXzgLVOmD0U6hWLc0dsZRxAf coveralls
